import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

// The head of index.html is the site's link preview and crawler metadata;
// these assertions keep the Open Graph image (generated by scripts/og-image.ts
// from scripts/og-image.svg) and the LLM entry point advertised.
const html = readFileSync(resolve(process.cwd(), "index.html"), "utf8");

describe("index.html metadata", () => {
	it("advertises the Open Graph image with its dimensions", () => {
		expect(html).toMatch(
			/property="og:image" content="%SITE_URL%\/og-image\.png"/,
		);
		expect(html).toMatch(/property="og:image:width" content="1200"/);
		expect(html).toMatch(/property="og:image:height" content="630"/);
		expect(html).toMatch(/property="og:image:alt"/);
	});

	it("advertises the Twitter large-image card", () => {
		expect(html).toMatch(/name="twitter:card" content="summary_large_image"/);
		expect(html).toMatch(
			/name="twitter:image" content="%SITE_URL%\/og-image\.png"/,
		);
	});

	it("links the LLM entry point and canonical URL", () => {
		expect(html).toMatch(/rel="alternate"[^>]*%SITE_URL%\/llms\.txt/);
		expect(html).toMatch(/rel="canonical" href="%SITE_URL%\/"/);
	});
});
