#!/usr/bin/env bash
# Tests setup.sh and install.sh in a throwaway HOME: install, idempotent
# re-run, dry run, pruning, the opencode symlink replacement, uninstall, and
# that directories the scripts didn't create are left alone. Called by
# scripts/check.sh.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT

export HOME="$SANDBOX/home"
export CLAUDE_SKILLS_DIR="$HOME/.claude/skills"
export OPENCODE_SKILLS_DIR="$HOME/.config/opencode/skills"
export OPENCODE_COMMANDS_DIR="$HOME/.config/opencode/commands"
unset XDG_DATA_HOME AI_GENT_DIR AI_GENT_REPO AI_GENT_BRANCH

failures=0
check() { # check <description> <command...>
  local what="$1"
  shift
  if "$@"; then
    printf '      ok    %s\n' "$what"
  else
    printf '      FAIL  %s\n' "$what"
    failures=$((failures + 1))
  fi
}

setup() { "$REPO_DIR/setup.sh" "$@" >"$SANDBOX/out" 2>&1; }
snapshot() { (cd "$HOME" && find . -print0 | sort -z | xargs -0 ls -ld --time-style=+ 2>/dev/null); }
links_into() { find "$1" -maxdepth 1 -type l -lname "$2/*" | wc -l; }

count() { { find "$@" 2>/dev/null || true; } | wc -l; }
skills=$(count "$REPO_DIR/skills" -mindepth 2 -maxdepth 2 -name SKILL.md)
plugins=$(count "$REPO_DIR/plugins" -mindepth 3 -maxdepth 3 -path '*/.claude-plugin/plugin.json')
plugin_skills=$(count "$REPO_DIR/plugins" -mindepth 4 -maxdepth 4 -path '*/skills/*/SKILL.md')

# Things the user owns, which must survive everything below.
mkdir -p "$CLAUDE_SKILLS_DIR/mine" "$CLAUDE_SKILLS_DIR/synced/one" "$OPENCODE_COMMANDS_DIR"
echo "own" >"$CLAUDE_SKILLS_DIR/mine/SKILL.md"
echo "own" >"$OPENCODE_COMMANDS_DIR/mine.md"
# A symlink from opencode's skills dir to Claude's, which setup.sh replaces.
mkdir -p "$(dirname "$OPENCODE_SKILLS_DIR")"
ln -s "$CLAUDE_SKILLS_DIR" "$OPENCODE_SKILLS_DIR"

echo "      -- dry run"
before="$(snapshot)"
setup --dry-run
check "changes nothing" test "$before" == "$(snapshot)"

echo "      -- install"
setup
check "claude: one link per skill and plugin" test "$(links_into "$CLAUDE_SKILLS_DIR" "$REPO_DIR")" -eq $((skills + plugins))
check "opencode: skills dir is now a real directory" test ! -L "$OPENCODE_SKILLS_DIR" -a -d "$OPENCODE_SKILLS_DIR"
check "opencode: one link per personal skill" test "$(links_into "$OPENCODE_SKILLS_DIR" "$REPO_DIR")" -eq "$skills"
check "opencode: synced linked" test -L "$OPENCODE_SKILLS_DIR/synced"
check "opencode: one generated entry per plugin skill" \
  test "$(find "$OPENCODE_SKILLS_DIR" -mindepth 2 -maxdepth 2 -name .ai-gent-generated | wc -l)" -eq "$plugin_skills"
check "opencode: one generated command per plugin skill" \
  test "$(grep -l 'Generated by ai-gent/setup.sh' "$OPENCODE_COMMANDS_DIR"/*.md | wc -l)" -eq "$plugin_skills"
check "generated entries point at existing sources" bash -c '
  for f in "$1"/*/SKILL.md; do
    [[ -f "$(dirname "$f")/.ai-gent-generated" ]] || continue
    src=$(sed -n "s/^  source: \"\(.*\)\"$/\1/p" "$f"); [[ -f "$src" ]] || exit 1
  done' _ "$OPENCODE_SKILLS_DIR"

echo "      -- re-run"
setup
check "idempotent (nothing linked or generated)" bash -c '! grep -Eq "^(link|relink|generate|backup) " "$1"' _ "$SANDBOX/out"

echo "      -- prune"
ln -s "$REPO_DIR/plugins/gone" "$CLAUDE_SKILLS_DIR/gone"
mkdir -p "$OPENCODE_SKILLS_DIR/gone-skill"
printf -- '---\nname: gone-skill\nmetadata:\n  source: "%s"\n---\n' "$REPO_DIR/plugins/gone/skills/skill/SKILL.md" \
  >"$OPENCODE_SKILLS_DIR/gone-skill/SKILL.md"
touch "$OPENCODE_SKILLS_DIR/gone-skill/.ai-gent-generated"
echo "<!-- Generated by ai-gent/setup.sh. -->" >"$OPENCODE_COMMANDS_DIR/gone-skill.md"
setup
check "stale claude link removed" test ! -L "$CLAUDE_SKILLS_DIR/gone"
check "stale opencode entry and command removed" test ! -e "$OPENCODE_SKILLS_DIR/gone-skill" -a ! -e "$OPENCODE_COMMANDS_DIR/gone-skill.md"

echo "      -- skip without --force"
rm "$CLAUDE_SKILLS_DIR/qa"
mkdir "$CLAUDE_SKILLS_DIR/qa"
setup
check "real directory in the way is kept" test -d "$CLAUDE_SKILLS_DIR/qa" -a ! -L "$CLAUDE_SKILLS_DIR/qa"
setup --force
check "--force backs it up and links" bash -c 'test -L "$1/qa" && compgen -G "$1/qa.bak-*" >/dev/null' _ "$CLAUDE_SKILLS_DIR"
rm -rf "$CLAUDE_SKILLS_DIR"/qa.bak-*

echo "      -- uninstall"
setup --uninstall
check "claude: no links into the repo" test "$(links_into "$CLAUDE_SKILLS_DIR" "$REPO_DIR")" -eq 0
check "opencode: no links, entries or commands left" bash -c '
  ! find "$1" -maxdepth 1 -type l -lname "$3/*" | grep -q . &&
  ! compgen -G "$1/*/.ai-gent-generated" >/dev/null &&
  ! grep -lq "Generated by ai-gent/setup.sh" "$2"/*.md 2>/dev/null' _ "$OPENCODE_SKILLS_DIR" "$OPENCODE_COMMANDS_DIR" "$REPO_DIR"
check "user's own files kept" test -f "$CLAUDE_SKILLS_DIR/mine/SKILL.md" -a -d "$CLAUDE_SKILLS_DIR/synced/one" -a -f "$OPENCODE_COMMANDS_DIR/mine.md"

# opencode config: the V2 permission rules, the guard plugin and the skill
# denies are merged into opencode.json, and undone on --uninstall.
oc_run() { # oc_run <home> <setup.sh args...>
  local home="$1"
  shift
  env HOME="$home" XDG_STATE_HOME="$home/.local/state" \
    CLAUDE_SKILLS_DIR="$home/.claude/skills" \
    OPENCODE_SKILLS_DIR="$home/.config/opencode/skills" OPENCODE_COMMANDS_DIR="$home/.config/opencode/commands" \
    "$REPO_DIR/setup.sh" "$@" >"$SANDBOX/out" 2>&1
}
json_get() { python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(json.dumps(eval(sys.argv[2], {"d": d})))' "$@"; }

echo "      -- opencode config"
h="$SANDBOX/oc"
mkdir -p "$h/.config/opencode"
cfg="$h/.config/opencode/opencode.json"
printf '{\n  "model": "x",\n  "permissions": [\n    { "action": "shell", "resource": "git push*", "effect": "deny" }\n  ]\n}\n' >"$cfg"
cp "$cfg" "$SANDBOX/cfg.orig"

oc_run "$h"
check "no terminal, no --yes: nothing edited" cmp -s "$SANDBOX/cfg.orig" "$cfg"
check "no terminal: the rules and plugin are printed" grep -q -F 'git commit*--no-verify*' "$SANDBOX/out"
check "no terminal: the plugin path is printed" grep -q -F 'opencode/guard' "$SANDBOX/out"

oc_run "$h" --dry-run --yes
check "--dry-run writes nothing" cmp -s "$SANDBOX/cfg.orig" "$cfg"

oc_run "$h" --yes
check "user's conflicting rule kept" test "$(json_get "$cfg" 'd["permissions"][0]["resource"]')" == '"git push*"'
check "conflict reported" grep -q -F 'git push*: yours is deny, kept' "$SANDBOX/out"
check "missing rules appended after the user's" test "$(json_get "$cfg" 'len(d["permissions"]) > 1')" == 'true'
check "a deny rule was added" test "$(json_get "$cfg" 'any(r["resource"] == "pg_restore*" for r in d["permissions"])')" == 'true'
check "read and edit denies for the credentials dir" test "$(json_get "$cfg" 'sorted(r["action"] for r in d["permissions"] if r["resource"] == "~/.config/ai-gent/*")')" == '["edit", "read"]'
check "skill denies hide the short IDs" test "$(json_get "$cfg" 'sorted(r["resource"] for r in d["permissions"] if r["action"] == "skill" and r["resource"] in ("spec", "build", "review"))')" == '["build", "review", "spec"]'
check "other settings kept" test "$(json_get "$cfg" 'd["model"]')" == '"x"'
check "a backup was kept" bash -c 'compgen -G "$1.bak-*" >/dev/null' _ "$cfg"
check "the guard plugin is registered" test "$(json_get "$cfg" 'd["plugins"]')" == '["'"$REPO_DIR"'/opencode/guard"]'

cp "$cfg" "$SANDBOX/cfg.merged"
oc_run "$h" --yes
check "re-run: idempotent" cmp -s "$SANDBOX/cfg.merged" "$cfg"
check "re-run: reports ok" grep -q -F 'ok       opencode guard rules and plugin' "$SANDBOX/out"

oc_run "$h" --uninstall
check "uninstall: only the added rules removed" test "$(json_get "$cfg" 'd')" == '{"model": "x", "permissions": [{"action": "shell", "resource": "git push*", "effect": "deny"}]}'
rm -f "$cfg".bak-*

printf '{\n  // mine\n  "model": "x"\n}\n' >"$cfg"
cp "$cfg" "$SANDBOX/cfg.jsonc"
oc_run "$h" --yes
check "a file with comments is left alone, snippet printed" cmp -s "$SANDBOX/cfg.jsonc" "$cfg"
check "a file with comments: snippet printed" grep -q -F 'has comments' "$SANDBOX/out"

printf '{ "permissions": "ask" }\n' >"$cfg"
oc_run "$h" --yes
check "a non-array permissions is left alone" test "$(json_get "$cfg" 'd')" == '{"permissions": "ask"}'

rm -f "$cfg"
oc_run "$h" --yes
check "no config: created with the rules" test "$(json_get "$cfg" 'any(r["resource"] == "pg_restore*" for r in d["permissions"])')" == 'true'
check "no config: created with the plugin" test "$(json_get "$cfg" 'd["plugins"]')" == '["'"$REPO_DIR"'/opencode/guard"]'
oc_run "$h" --uninstall
check "uninstall: a created, untouched config is removed" test ! -e "$cfg"

echo "      -- install.sh (clone, then update)"
AI_GENT_REPO="$REPO_DIR" sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1 || cat "$SANDBOX/out"
clone="$HOME/.local/share/ai-gent"
check "clones into the default directory" test -f "$clone/setup.sh"
cloned=$(count "$clone/skills" "$clone/plugins" -mindepth 1 -maxdepth 1 -type d)
check "links point into the clone" test "$(links_into "$CLAUDE_SKILLS_DIR" "$clone")" -eq "$cloned"
AI_GENT_REPO="$REPO_DIR" sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1
check "re-run updates in place" grep -q "updating $clone" "$SANDBOX/out"
echo "local change" >>"$clone/README.md"
AI_GENT_REPO="$REPO_DIR" sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1
check "local changes are left alone" grep -q "local changes" "$SANDBOX/out"
mkdir -p "$SANDBOX/not-a-clone"
check "refuses a non-clone directory" bash -c '! AI_GENT_DIR="$1" AI_GENT_REPO="$2" sh "$2/install.sh" >/dev/null 2>&1' _ "$SANDBOX/not-a-clone" "$REPO_DIR"

echo "      -- install.sh (pin a tag, then move the pin)"
src="$SANDBOX/src"
pinned="$SANDBOX/pinned"
g() { git -C "$src" -c user.name=test -c user.email=test@example.test "$@"; }
git clone -q "$REPO_DIR" "$src"
# Annotated tags on their own commits, like real releases (describe prefers
# annotated tags, so sharing a commit with the repo's own tags would be ambiguous).
g commit -q --allow-empty -m "chore: release 9.9.0"
g tag -a 9.9.0 -m 9.9.0
g commit -q --allow-empty -m "chore: release 9.9.1"
g tag -a 9.9.1 -m 9.9.1
AI_GENT_DIR="$pinned" AI_GENT_REPO="$src" AI_GENT_BRANCH=9.9.0 sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1
check "clones at the tag" test "$(git -C "$pinned" rev-parse HEAD)" == "$(g rev-parse '9.9.0^{commit}')"
AI_GENT_DIR="$pinned" AI_GENT_REPO="$src" sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1
check "stays pinned without AI_GENT_BRANCH" grep -q "pinned to 9.9.0" "$SANDBOX/out"
AI_GENT_DIR="$pinned" AI_GENT_REPO="$src" AI_GENT_BRANCH=9.9.1 sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1
check "moves the pin to a newer tag" test "$(git -C "$pinned" rev-parse HEAD)" == "$(g rev-parse '9.9.1^{commit}')"

exit $((failures > 0))
