#!/usr/bin/env bash
# Tests setup.sh and install.sh in a throwaway HOME: install, idempotent
# re-run, dry run, pruning, the opencode symlink replacement, uninstall, and
# that directories the scripts didn't create are left alone. Called by
# scripts/check.sh.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT

export HOME="$SANDBOX/home"
export CLAUDE_SKILLS_DIR="$HOME/.claude/skills"
export OPENCODE_SKILLS_DIR="$HOME/.config/opencode/skills"
export OPENCODE_COMMANDS_DIR="$HOME/.config/opencode/commands"
export OPENCODE_DISABLE_CLAUDE_CODE_SKILLS=1
unset XDG_DATA_HOME AI_GENT_DIR AI_GENT_REPO AI_GENT_BRANCH

failures=0
check() { # check <description> <command...>
  local what="$1"
  shift
  if "$@"; then
    printf '      ok    %s\n' "$what"
  else
    printf '      FAIL  %s\n' "$what"
    failures=$((failures + 1))
  fi
}

setup() { "$REPO_DIR/setup.sh" "$@" >"$SANDBOX/out" 2>&1; }
snapshot() { (cd "$HOME" && find . -print0 | sort -z | xargs -0 ls -ld --time-style=+ 2>/dev/null); }
links_into() { find "$1" -maxdepth 1 -type l -lname "$2/*" | wc -l; }

count() { { find "$@" 2>/dev/null || true; } | wc -l; }
skills=$(count "$REPO_DIR/skills" -mindepth 2 -maxdepth 2 -name SKILL.md)
plugins=$(count "$REPO_DIR/plugins" -mindepth 3 -maxdepth 3 -path '*/.claude-plugin/plugin.json')
plugin_skills=$(count "$REPO_DIR/plugins" -mindepth 4 -maxdepth 4 -path '*/skills/*/SKILL.md')

# Things the user owns, which must survive everything below.
mkdir -p "$CLAUDE_SKILLS_DIR/mine" "$CLAUDE_SKILLS_DIR/synced/one" "$OPENCODE_COMMANDS_DIR"
echo "own" >"$CLAUDE_SKILLS_DIR/mine/SKILL.md"
echo "own" >"$OPENCODE_COMMANDS_DIR/mine.md"
# A symlink from opencode's skills dir to Claude's, which setup.sh replaces.
mkdir -p "$(dirname "$OPENCODE_SKILLS_DIR")"
ln -s "$CLAUDE_SKILLS_DIR" "$OPENCODE_SKILLS_DIR"

echo "      -- dry run"
before="$(snapshot)"
setup --dry-run
check "changes nothing" test "$before" == "$(snapshot)"

echo "      -- install"
setup
check "claude: one link per skill and plugin" test "$(links_into "$CLAUDE_SKILLS_DIR" "$REPO_DIR")" -eq $((skills + plugins))
check "opencode: skills dir is now a real directory" test ! -L "$OPENCODE_SKILLS_DIR" -a -d "$OPENCODE_SKILLS_DIR"
check "opencode: one link per personal skill" test "$(links_into "$OPENCODE_SKILLS_DIR" "$REPO_DIR")" -eq "$skills"
check "opencode: synced linked" test -L "$OPENCODE_SKILLS_DIR/synced"
check "opencode: one generated entry per plugin skill" \
  test "$(find "$OPENCODE_SKILLS_DIR" -mindepth 2 -maxdepth 2 -name .ai-gent-generated | wc -l)" -eq "$plugin_skills"
check "opencode: one generated command per plugin skill" \
  test "$(grep -l 'Generated by ai-gent/setup.sh' "$OPENCODE_COMMANDS_DIR"/*.md | wc -l)" -eq "$plugin_skills"
check "generated entries point at existing sources" bash -c '
  for f in "$1"/*/SKILL.md; do
    [[ -f "$(dirname "$f")/.ai-gent-generated" ]] || continue
    src=$(sed -n "s/^  source: \"\(.*\)\"$/\1/p" "$f"); [[ -f "$src" ]] || exit 1
  done' _ "$OPENCODE_SKILLS_DIR"

echo "      -- re-run"
setup
check "idempotent (nothing linked or generated)" bash -c '! grep -Eq "^(link|relink|generate|backup) " "$1"' _ "$SANDBOX/out"

echo "      -- prune"
ln -s "$REPO_DIR/plugins/gone" "$CLAUDE_SKILLS_DIR/gone"
mkdir -p "$OPENCODE_SKILLS_DIR/gone-skill"
printf -- '---\nname: gone-skill\nmetadata:\n  source: "%s"\n---\n' "$REPO_DIR/plugins/gone/skills/skill/SKILL.md" \
  >"$OPENCODE_SKILLS_DIR/gone-skill/SKILL.md"
touch "$OPENCODE_SKILLS_DIR/gone-skill/.ai-gent-generated"
echo "<!-- Generated by ai-gent/setup.sh. -->" >"$OPENCODE_COMMANDS_DIR/gone-skill.md"
setup
check "stale claude link removed" test ! -L "$CLAUDE_SKILLS_DIR/gone"
check "stale opencode entry and command removed" test ! -e "$OPENCODE_SKILLS_DIR/gone-skill" -a ! -e "$OPENCODE_COMMANDS_DIR/gone-skill.md"

echo "      -- skip without --force"
rm "$CLAUDE_SKILLS_DIR/qa"
mkdir "$CLAUDE_SKILLS_DIR/qa"
setup
check "real directory in the way is kept" test -d "$CLAUDE_SKILLS_DIR/qa" -a ! -L "$CLAUDE_SKILLS_DIR/qa"
setup --force
check "--force backs it up and links" bash -c 'test -L "$1/qa" && compgen -G "$1/qa.bak-*" >/dev/null' _ "$CLAUDE_SKILLS_DIR"
rm -rf "$CLAUDE_SKILLS_DIR"/qa.bak-*

echo "      -- uninstall"
setup --uninstall
check "claude: no links into the repo" test "$(links_into "$CLAUDE_SKILLS_DIR" "$REPO_DIR")" -eq 0
check "opencode: no links, entries or commands left" bash -c '
  ! find "$1" -maxdepth 1 -type l -lname "$3/*" | grep -q . &&
  ! compgen -G "$1/*/.ai-gent-generated" >/dev/null &&
  ! grep -lq "Generated by ai-gent/setup.sh" "$2"/*.md 2>/dev/null' _ "$OPENCODE_SKILLS_DIR" "$OPENCODE_COMMANDS_DIR" "$REPO_DIR"
check "user's own files kept" test -f "$CLAUDE_SKILLS_DIR/mine/SKILL.md" -a -d "$CLAUDE_SKILLS_DIR/synced/one" -a -f "$OPENCODE_COMMANDS_DIR/mine.md"

echo "      -- install.sh (clone, then update)"
AI_GENT_REPO="$REPO_DIR" sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1 || cat "$SANDBOX/out"
clone="$HOME/.local/share/ai-gent"
check "clones into the default directory" test -f "$clone/setup.sh"
cloned=$(count "$clone/skills" "$clone/plugins" -mindepth 1 -maxdepth 1 -type d)
check "links point into the clone" test "$(links_into "$CLAUDE_SKILLS_DIR" "$clone")" -eq "$cloned"
AI_GENT_REPO="$REPO_DIR" sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1
check "re-run updates in place" grep -q "updating $clone" "$SANDBOX/out"
echo "local change" >>"$clone/README.md"
AI_GENT_REPO="$REPO_DIR" sh "$REPO_DIR/install.sh" --target claude >"$SANDBOX/out" 2>&1
check "local changes are left alone" grep -q "local changes" "$SANDBOX/out"
mkdir -p "$SANDBOX/not-a-clone"
check "refuses a non-clone directory" bash -c '! AI_GENT_DIR="$1" AI_GENT_REPO="$2" sh "$2/install.sh" >/dev/null 2>&1' _ "$SANDBOX/not-a-clone" "$REPO_DIR"

exit $((failures > 0))
